# Generated by Django 3.2.6 on 2021-08-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0030_alter_doctorinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
