# Generated by Django 3.2.6 on 2021-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0033_auto_20210901_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='fullName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
