# Generated by Django 3.2.6 on 2022-01-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0034_alter_patientinfo_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=256, null=True),
        ),
    ]
