# Generated by Django 3.2.6 on 2022-02-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0037_alter_patientinfo_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='bloodGroup',
            field=models.BinaryField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], null=True),
        ),
    ]
