# Generated by Django 3.2.6 on 2022-02-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0042_alter_patientinfo_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='doctorsPP'),
        ),
    ]
