# Generated by Django 3.2.6 on 2022-02-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0043_alter_doctorinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='image',
            field=models.ImageField(blank=True, default='D:\\Projects\\pythonProject\\Smart-Health\\healthcareSystem\\static\\img\\default.png', null=True, upload_to='doctorsPP'),
        ),
    ]
