# Generated by Django 3.2.6 on 2022-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0045_alter_doctorinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='image',
            field=models.ImageField(default='img/default.png', upload_to='doctorsPP'),
        ),
    ]
