# Generated by Django 3.2.6 on 2023-01-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0047_alter_doctorinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='visitingHours',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=100, null=True),
        ),
    ]
