# Generated by Django 3.2.6 on 2023-01-11 08:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareApp', '0051_auto_20230110_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='visitingHours',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=10, null=True), max_length=66, null=True, size=6),
        ),
        migrations.DeleteModel(
            name='VisitTime',
        ),
    ]
